<?php
/**
 * @file
 * Code for the Search feature.
 */

include_once 'mini_search.features.inc';
/**
 * Implements hook_block_info_alter().
 */
function mini_search_block_info_alter(&$blocks, $theme, $code_blocks) {
  // TODO: Removes core search block.
//   unset($blocks['search']['form']);
  if ($theme == 'minorite' || $theme == 'minorite_html4') {
    // Enables search block on header.
    $blocks['mini_search']['header']['status'] = 1;
    $blocks['mini_search']['header']['region'] = 'header';
    // Enables search block on bottom.
    $blocks['mini_search']['bottom']['status'] = 1;
    $blocks['mini_search']['bottom']['region'] = 'bottom';
  }
}

/**
 * Implements hook_block_info().
 */
function mini_search_block_info() {
  $blocks = array();

  $blocks['header'] = array(
      'info' => t('Header search'),
      'cache' => DRUPAL_CACHE_GLOBAL,
  );

  $blocks['bottom'] = array(
      'info' => t('Bottom search'),
      'cache' => DRUPAL_CACHE_GLOBAL,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function mini_search_block_view($delta = '') {
  $block['content'] = 'dummy content';
  $block['subject'] = t('Search');
  return $block;
}
/**
 * hook form alter on the views exposed form on the search page, to customize
 */
function mini_search_form_views_exposed_form_alter(&$form, &$form_state) {
  if ($form['#id'] == 'views-exposed-form-search-page') {
    // Champ mot clé
    $form['search_api_views_fulltext']['#size'] = '';
    $form['search_api_views_fulltext']['#attributes'] = array('placeholder' => array(t('Enter a keyword')));
    $form['title']['#size']='';
    $form['title']['#attributes'] = array('placeholder' => array(t('Enter a title')));
    // Item par page
    $form['items_per_page']['#type'] = 'hidden';
    if (isset($form_state['input']['items_per_page'])) {
      $form['items_per_page']['#value'] = $form_state['input']['items_per_page'];
    }
    // Filtrer
    $form['reset']['#attributes']['class']  = array('button-ico-eraser');
    $form['submit']['#attributes']['class'] = array('button-ico-magnifier');
    $form['submit']['#value'] = t('Search');
  }
}
/**
 * Define a dummy form with "Items per page" form item.
 *
 * It will only be used to fill in the corresponding form item (hidden) of Views exposed form
 */
function mini_search_items_per_page() {
  $pager_options = array(
      10 => t('!n results per page', array('!n' => 10)),
      15 => t('!n results per page', array('!n' => 15)),
      20 => t('!n results per page', array('!n' => 20)),
  );
  $form['items_per_page'] = array(
      '#type' => 'select',
      '#options' => $pager_options,
      '#default_value' => empty($_GET['items_per_page']) ? 10 : $_GET['items_per_page'],
      '#title' => t('Display'),
      '#attributes' => array('onchange' => 'jQuery("input[name=\"items_per_page\"]").val(jQuery("#edit-items-per-page").val()); jQuery("#edit-submit-search").click();'),
  );
  return $form;
}